services:
  app:
    build: .
    container_name: losev-takip-app
    restart: always
    volumes:
      - app-data:/app/data
    networks:
      - losev-network
    environment:
      - NODE_ENV=production
      - PORT=4000
      - DB_PATH=/app/data/database.sqlite

  nginx:
    image: nginx:alpine
    container_name: losev-takip-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"  # SSL için
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro  # SSL sertifikaları
    networks:
      - losev-network
    depends_on:
      - app

volumes:
  app-data:

networks:
  losev-network:
    driver: bridge
